### PR TITLE
Reworking changes around Mount Manager and GIO Extension

### PR DESCRIPTION
**Pull request by cmallwitz**
I have tested this while
- mounting/unmounting volumes from Nautilus
- mounting/unmounting using Mount Manager widget and the "Unmount" menu item
- getting file properties (right mouse click menu)
- starting file viewer (F3) on files

I've tried to cover loads of combinations around ftp, archive and MTP (cell phone) mounts.

A few lines may actually be "left overs" from adding MTP and Archive GIO provider support earlier.

### CODE REVIEW

**Comment by cmallwitz** [comment]
Caveat: I'm not saying that is all of it...

**Comment by MeanEYE** [comment]
Oh that's a lot of fixes. I am unable to test MTP at the moment. I shoved Android 6.0.1 on it :D and kind of broke USB support. But I'll go over these in upcoming days and merge. Great work. Perhaps some of these lines should broken into simpler code and local temporary variables. I'll check, GitHub has a really bad code display.

**Comment by cmallwitz** [comment]
Yep, after I started a few lines here and there - I realized that too. But
the changes are in one area and they kind of go together. I used an archive
mounted tar file and a public anonymous ftp web site to test it. The
archive mount is kind of nice because it hits the GIO layer just like
FTP/Samba.etc but doesn't need network and username/passwords which makes
it easier to use while testing.

A note on archive mounts: an URI like
archive://file%253A%252F%252F%252Ftmp%252Fsunflower%252Ftest.tar.gz/ is
"double" urllib.quoted() after the 'archive://' bit (the : in archive:// is
not qouted) - even while a (single quoted)
archive://file%3A%2F%2F%2Ftmp%2Fsunflower%2Ftest.tar.gz/ is used for
display in some places - the double quoted version is needed to get it to
work e.g. when referencing it in GIO calls...

Christian

**Comment by MeanEYE** [comment]
Okay, thanks for testing. It's weird as hell. Didn't know we need double quoted.

**Comment by cmallwitz** [comment]
Replacing this to fix tiny problem.

**Pull request closed without merging**
