### PR TITLE
GTK3 fixes for find file extension

### PR DESCRIPTION
**Pull request by cmallwitz**

### CODE REVIEW

**Comment by cmallwitz** [comment]
Reworked method call with named parameter include_hidden_chars
https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-get-text

**Comment by MeanEYE** [comment]
Good. Shorter and more descriptive. If you name that parameter it can be reverted to previous one line form. Then I'll merge.

**Comment by cmallwitz** [comment]
I think the PR has already been updated (see above) - commit hash 2040c8c

**Comment by MeanEYE** [comment]
Ah, okay. It didn't it show it initially.

**Pull request merged**
