### PR TITLE
Fix up ops for GTK3

### PR DESCRIPTION
**Pull request by cmallwitz**
Fixed up for file rename - change to import and global replace of GObject with GLib

### CODE REVIEW

**Comment by MeanEYE** [comment]
Why switch to GLib? It's additional requirement for no reason.

**Comment by cmallwitz** [comment]
Oh - it was already used in line 1748 and missing in the imports.
file_list.py has it too. And Gio is returning GLib.GError as exceptions

But maybe I'm missing something here - I'm not quite clear what the
difference is between GLib vs. GObject. Do you have point to read up on?

I tried GObject.idle_add() and it seems to do the same job. Do you actively
avoid GLib?

Cheers
Christian

**Comment by MeanEYE** [comment]
Well, `GObject.idle_add` is proxy for `GLib` one. I just like avoiding extra dependency. They are essentially the same. Chances are `gir` package for `GLib` is installed along with `GObject`, but still, any import from `gi.repository` requires matching `gir` file (introspection resource). Since `GLib` is rarely used in Sunflower, it's not really useful to import whole module, which is not small by the way, just for the sake of that one method which is available in `GObject`.

**Comment by cmallwitz** [comment]
Switched from GLib to GObject - a lot less lines changed this way.

**Pull request merged**
