### PR TITLE
Issues 217 - Fix for handling file names with non ASCII characers

### PR DESCRIPTION
**Pull request by cmallwitz**
I think this is the best solution for us to fix issue 217 - see my comments there.

### CODE REVIEW

**Comment by MeanEYE** [comment]
Why is there `reload`?

**Comment by cmallwitz** [comment]
Because Python is trying to be smarter than everyone else - see details of
https://github.com/MeanEYE/Sunflower/issues/217 - python removes the method
setdefaultencoding() after it calls it once at start up - without the
reload() it is not available.

Christian

**Comment by MeanEYE** [comment]
Isn't there a different way to set default encoding?

**Comment by cmallwitz** [comment]
Not that I could find - apparently this is the one (admittedly very hacky)
way to change the default encoding used by Python to deal with String to
Unicode conversions.

Christian

**Comment by MeanEYE** [comment]
Will this loading solve the issue we've had with invalid utf-8 file and directory names?

**Comment by cmallwitz** [comment]
We had multiple issues with file/directory names but this is the only one
I'm aware of concerning UTF-8 (really non-ASCII) characters in name. And
yes, this fix should address all issues (known and unknown) where we
convert a string containing non-ASCII UTF-8 characters internally (received
from Gtk) and try to convert to Unicode - python will use the default
encoding at this point and fail without the fix.

Christian

**Pull request merged**
