### PR TITLE
File list: Hide files listed in .hidden. Close MeanEYE/Sunflower#132

### PR DESCRIPTION
**Pull request by ArseniyK**

### CODE REVIEW

**Comment by MeanEYE** [comment]
This patch wont work because `.splitlines` keeps the `\n` after splitting. So matching file name against entry in the list will fail.

**Comment by ArseniyK** [comment]
splitlines() dont kepp '\n', readlines() does

**Comment by MeanEYE** [comment]
Ah you are right.

**Comment by MeanEYE** [comment]
I am not familiar with `.hidden`. Should we support wildcards such as `*` and `?`?

**Comment by ArseniyK** [comment]
.hidden just keep filenames without wildcards

**Comment by ArseniyK** [comment]
UPD

**Pull request merged**
