### PR TITLE
Add pylint rules

### PR DESCRIPTION
**Pull request by joshas**
Let's add linting rules to improve source code quality and catch errors early. This is a biased rules config, I tried adjusting it to Coding Style rules from Sunflower Wiki. Please review it as some rules still might need adjusting.

### CODE REVIEW

**Comment by MeanEYE** [comment]
Good idea. Does the current code pass?

**Comment by joshas** [comment]
No, there's quite some work to be done for the code to pass. I think we will have to tweak pylint rules a little, to remove unnecessary checks, e.g. module documentation strings and similar.

**Comment by MeanEYE** [comment]
Okay, how do you run this test, just executing `pylint`?

**Comment by joshas** [comment]
`pylint sunflower` should check files in all modules, but that might be a huge output, considering there are many inconsistencies in code. It would probably be a good idea to check a few main files, modify ruleset and then fix up all remaining codebase.
Some IDEs might pick up pylint rules and automatically highlight issues right in editor.

**Comment by MeanEYE** [comment]
Just checked and yes, there's a huge amount of output. Some reported issues are valid, others not so much. We should do as you suggest. Check main file, then adapt.

**Pull request merged**
