### PR TITLE
Switch to Python 3

### LINKED ISSUE #298: Move to Python 3
Do you plan to convert code to Python 3? Python 2 will become obsolete in 20 months.
https://pythonclock.org/

### PR DESCRIPTION
**Pull request by tjol**
This is a tentative port to Python 3 (resolves #298). It works, but I imagine there are some regressions here and there. Some notes:

- No effort made to keep Python 2 support. As sunflower isn't a library, there's really no point.
- When changing the imports to match Python 3's absolute import semantics, I took the liberty of turning the ‘application’ directory into a package, ‘sunflower’. Apart from being the usual thing to do, this would allow eventually distributing sunflower via pip, and even installing plugins with pip (using PEP 420) — if desired.
- The main difficulty is (and remains) support for non-UTF-8 file names (strictly speaking: file names that cannot be decoded with the system locale). With Python 2, these eventually caused Pango to complain, but otherwise didn't cause too much trouble. 
   
   With Python 3, they create some contention at the Python/GObject boundary: undecodable file names are represented with surrogate codepoints which PyGObject flatly refuses to marshall. However, APIs which expect file names can be called with bytes (if the gir definitions are correct). This means:
    * All filenames used *as filenames* have to be explicitly encoded before passing to Gio/Gtk
    * All filenames used in the user interface have to have their surrogate characters replaced before passing to Gtk.
   
   This is what the functions `sunflower.common.disp_fn()` and `sunflower.common.encode_fn()` are for. The approach I took for displaying invalid bytes in filenames was to replace them all with ‘�’.

### CODE REVIEW

**Comment by MeanEYE** [comment]
Thanks. I'll go over this pull request later today and merge if there are no big regressions. Otherwise I'll just create a new branch where these new issues can be resolved.

**Comment by awaken1ng** [comment]
Found the following issues after a bit of using:

- Opening directories with hidden files with `Show hidden files` enabled will reliably crash Sunflower with:
  ```
  Gtk:ERROR:gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
  Aborted (core dumped)
  ```
  After a bit of poking around, [it seems to be crashing when flushing the queue](https://github.com/MeanEYE/Sunflower/blob/d4a6abc6d77e5caed587712354af01497e0c20ac/sunflower/plugins/file_list/file_list.py#L1731)
  Doesn't seem to be as much of the problem on `master` branch, although it somehow crashed once after saving the setting (same error)

  Sometimes still crashes with the same error when opening directories even with the `Show hidden files` disabled (happens on `master` as well)


- Some errors [will fail to report](https://github.com/MeanEYE/Sunflower/blob/d4a6abc6d77e5caed587712354af01497e0c20ac/sunflower/plugins/file_list/file_list.py#L2142) and render the tab unusable
  ``` python
  Exception in thread Thread-4:
  Traceback (most recent call last):
    File "/home/awakening/git/sunflower/sunflower/plugins/file_list/file_list.py", line 2137, in thread_method
      item_list = provider.list_dir(path)
    File "/home/awakening/git/sunflower/sunflower/plugins/file_list/local_provider.py", line 231, in list_dir
      return os.listdir(real_path)
  PermissionError: [Errno 13] Permission denied: '<edited out>'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.7/threading.py", line 865, in run
      self._target(*self._args, **self._kwargs)
    File "/home/awakening/git/sunflower/sunflower/plugins/file_list/file_list.py", line 2141, in thread_method
      print('Load directory error: ', error.message)
  AttributeError: 'PermissionError' object has no attribute 'message'
  ```
  Working around this will throw 
  ```python
    Traceback (most recent call last):
    File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.7/threading.py", line 865, in run
      self._target(*self._args, **self._kwargs)
    File "/home/awakening/git/sunflower/sunflower/plugins/file_list/file_list.py", line 2148, in thread_method
      with gtk.gdk.lock:
  NameError: name 'gtk' is not defined
  ```
  If you ignore the lock, the spinner will fail to hide and still break the tab 
  The `gtk` not defined part happens on `master` branch as well, so not exactly port fault

**Comment by tjol** [comment]
HI @awaken1ng,

Thanks for having a look! As far as I can tell, these issues are also present in the (Python 2) `develop` branch. Maybe a separate bug report is in order?

**Comment by awaken1ng** [comment]
Selecting items threw an exception, found 5 missed `xrange`s
https://github.com/MeanEYE/Sunflower/blob/b23f2f57645ae36be3aeec1673701fabf15b8fcc/sunflower/menus.py#L151
https://github.com/MeanEYE/Sunflower/blob/b23f2f57645ae36be3aeec1673701fabf15b8fcc/sunflower/gui/preferences/associations.py#L170
https://github.com/MeanEYE/Sunflower/blob/b23f2f57645ae36be3aeec1673701fabf15b8fcc/sunflower/plugins/sessions/plugin.py#L451
https://github.com/MeanEYE/Sunflower/blob/b23f2f57645ae36be3aeec1673701fabf15b8fcc/sunflower/plugins/sessions/plugin.py#L455
https://github.com/MeanEYE/Sunflower/blob/b23f2f57645ae36be3aeec1673701fabf15b8fcc/sunflower/plugins/file_list/file_list.py#L1558

**Comment by MeanEYE** [comment]
Thanks for testing this @awaken1ng. I will make a separate branch for this until we iron out these bugs.

**Comment by tjol** [comment]
Sorry for the delay — I think I've sorted out the issues @awaken1ng described above… let me know if i missed something!

**Comment by MeanEYE** [comment]
Great. I'll look into it. Thanks!

**Comment by tjol** [comment]
So you want to keep supporting Python 2? In that case I should do some more testing...

**Comment by tjol** [comment]
Come to think of it, it almost certainly won't work with Python 2 as-is because of the standard library reorganisation. But that shouldn't be too hard to sort out.

**Comment by MeanEYE** [comment]
I don't care so much about either version of Python as much as I care about default version across different distributions. Debian for example keeps 2.x default. Others probably 3.x. This means default modules such as GTK+, GLib and others will come pre-installed for default version. I would really like to avoid pulling dozens of packages as dependency.

However I do realize this is a hard problem to solve. I've been trying different approaches over the years and 2.x version proved to easiest to support with pretty much all distributions having it pre-installed and only few of them defaulting to 3.x. For that reason, if possible to have support for both, great as Python 3 is definitely coming, sometime. But given a single choice, I think I'd opt out for version 2, just for the sake of covering the most ground.

Am going to try and grab some time as soon as possible and go over this. Hopefully we can find some common solution for everyone.

**Comment by tjol** [comment]
Supporting both isn't all that hard in the end (see the other PR), but it is a bit ugly and makes maintaining the program (possibly a lot) more difficult. That doesn't matter really though. I'd be more concerned about the situation for plugins: switching to Gtk3 and switching to Python3 are both (potentially) breaking changes. I'd vote for forcing both at the same time.

As for you not having a lot of time right now — I get it. Don't worry about it. Obviously I've been throwing a lot of stuff that's not entirely obvious at your project recently with absolutely no warning.

**Comment by MeanEYE** [comment]
Supporting both would make our lives in some other aspect a lot easier. Right now there's a starter script which finds and tests all Python interpreters and then chooses the right one. With support for both versions we could get away with that and somewhat improve startup speed, memory usage and few other aspects.

Throwing new stuff is fine. It's a kick I really need as I have been somewhat neglecting my personal projects. This will force me to get back into full development again which I've been meaning to do for a while now.

**Comment by tjol** [comment]
Superseded by #313

**Pull request closed without merging**
