### PR TITLE
File list: Remove queue flushing from _add_item method. Fix MeanEYE/Sunflower#36

### PR DESCRIPTION
**Pull request by ArseniyK**
Queue flushing in _add_item slowdown direcory loading. Anyway we flush queue just after _add_item call. So queue flushing in _add_item is unnecesary.

### CODE REVIEW

**Comment by MeanEYE** [comment]
This is needed so user can still use the problem while directory is being loaded. If we waited for the whole directory to be loaded to present it then, there wouldn't be a point in doing threaded load in the first place. It slows down directory loading, but not significantly. Did you experience different results?

**Comment by MeanEYE** [comment]
Can you explain the logic behind this? It seems as you are focusing item whenever cursor is moved.

**Comment by ArseniyK** [comment]
after self._apply_sort_function() items moving in list change path and iter object may change too. Saving iter in variable and scroll to this iter outside self._flush_queue dont work.  So i scroll again to seleced iter also i can find iter by self._find_iter_by_name but i think it unnecessary loop through all elements.

**Comment by ArseniyK** [comment]
UPDATED

**Pull request merged**
