### PR TITLE
Gio archive mounter

### PR DESCRIPTION
**Pull request by cmallwitz**
Add support for GVFS Archive Mounter mounts - this just handles already mounted archives or archives being mounted. Thet URIs are kind of long and ugly looking so a few additional lines are required not to corrupt them.

TODO/Notes
- shorten URI in notebook tab - these are too long for archive:// URIs 
- (more general) if GVFS mounts get umounted, we should try to remove them from any notebook item to avoid users still trying to use them

### CODE REVIEW

**Comment by cmallwitz** [comment]
Another question: Nautilus knows that archive:// mounts are read-only and doesn't show rename/move/delete items in context menus and disables keys like F2 to rename a file. Can we do something like this easily in Sunflower too? Thanks Christian

**Comment by MeanEYE** [comment]
We can, but we can also rename and delete etc. My idea was to have archive schedule operations and present modified file system. So when archive is closed changes are applied. For example you rename file, add some new ones, delete stuff etc. You close archive all this is applied, files re-packed etc.

**Comment by cmallwitz** [comment]
This would work if we mount archives using FUSE (eg. fuse-zip) instead of GIO GVFS archive mounter which unfortunately is read-only. But I guess we take one step at a time...
Christian

**Comment by MeanEYE** [comment]
Yeah. Bad thing with relying on GIO or FUSE is relying on GIO and FUSE. You would be surprised how many things are half-done. I'll review this in next couple of days and merge or see how to proceed.

**Comment by cmallwitz** [comment]
You are absolutely right - GIO/GVFS is a good starting point for 
read-only access to most things. For FUSE there seem to be hundreds of 
plugins - 90% basically dead for a few years, but for read/write access 
for the mostly used archive formats we may be ok. We will see how far we 
get with this approach...

One probably has to think about how many dependencies one is adding to 
Sunflower - GIO/GVFS is always coming with Gnome.

Christian

**Comment by cmallwitz** [comment]
Hi Mladen, do you need any more information or input with this? Cheers Christian

**Comment by MeanEYE** [comment]
I don't think I need any more information. Sorry for the delay, project hogging all of my free time is finally in testing phase so am soon resuming my regular development of this project. That said, I have (I think) conflicting PR with this one. So I'll have to take a look.

**Comment by cmallwitz** [comment]
No problem - my other PR regarding gphoto2/mtp support may change some of
the same files but not actually overlap in code.

Thanks
Christian

**Comment by MeanEYE** [comment]
I had to do manual merge. Hence closing this PR.

**Pull request closed without merging**
