### PR TITLE
Do not open directories with viewer

### LINKED ISSUE #333: Pressing F3 on directory results in error in terminal
After pressing F3 (view command) on directory, following traceback and error message appears in terminal:

> Traceback (most recent call last):
  File "/home/virtualbox/dev/Sunflower/sunflower/accelerator_group.py", line 93, in _handle_activate
    result = callback_method(widget, label)
  File "/home/virtualbox/dev/Sunflower/sunflower/plugin_base/item_list.py", line 1416, in _view_selected
    Viewer(selection, self.get_provider(), self)
  File "/home/virtualbox/dev/Sunflower/sunflower/tools/viewer.py", line 31, in __init__
    data = associations_manager.get_sample_data(path, provider)
  File "/home/virtualbox/dev/Sunflower/sunflower/associations.py", line 100, in get_sample_data
    file_handle = provider.get_file_handle(path, Mode.READ)
  File "/home/virtualbox/dev/Sunflower/sunflower/plugins/file_list/local_provider.py", line 107, in get_file_handle
    return open(real_path, real_mode)
IsADirectoryError: [Errno 21] Is a directory: '/home/virtualbox/Desktop'

Error should be caught and not displayed. In the future it might be useful for "view" command to display detailed directory information, like in Total Commander.

### PR DESCRIPTION
**Pull request by joshas**
Added early check to viewer plugin if provided path is a directory.  Fixes #333

### CODE REVIEW

**Comment by MeanEYE** [comment]
This is not the right approach as it's relying on `os.path`. Viewer is already getting a `provider` as parameter which offers check if it's directory. However viewer plugins are not limited to files only, so ideally we should see if the viewer extensions support directory before resorting to such a check.

Where does the issue occur in specific in which case opening the empty window is preferable to whatever happens?

**Comment by joshas** [comment]
Without this fix when user presses F3 or clicks View command button error message in terminal is displayed. Actually nothing too serious and as I mentioned in original bug report, Total Commander viewer shows directory stats when directory is viewed. We might implement similar functionality.

**Comment by MeanEYE** [comment]
Okay. For starters `provider.is_dir` should be used to keep extended support for archives and remote paths.

**Comment by joshas** [comment]
I've replaced os.path.isdir function with one from provider.

**Pull request merged**
