### PR TITLE
Bs 2016 03 21

### PR DESCRIPTION
**Pull request by beschrade**
Changed some features i need:
- Opening files on sftp:
- Sorting of items
- Update option in copy and move operations
  I integrated and tested this in current master. Unfortunately i was not able to test this changes in develop, i cannot run the development branch on my machines.
## The first one (Ubuntu 12.03 LTS) stops with:

$ Sunflower/Sunflower.py
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
**
ERROR:/build/buildd/pygobject-3.2.2/gi/_gobject/pygobject.c:929:pygobject_new_full: assertion failed: (tp != NULL)
## The second one (OpenSuse 13.2) stops with:

> Sunflower/Sunflower.py
> Traceback (most recent call last):
>   File "Sunflower/application/main.py", line 41, in on_activate
>     from gui.main_window import MainWindow
>   File "/daten/wrk/sunflw/Sunflower/application/gui/main_window.py", line 19, in <module>
>     from associations import AssociationManager
>   File "/daten/wrk/sunflw/Sunflower/application/associations.py", line 12, in <module>
>     from plugin_base.terminal import TerminalType
>   File "/daten/wrk/sunflw/Sunflower/application/plugin_base/terminal.py", line 4, in <module>
>     gi.require_version('Vte', '2.90')
>   File "/usr/lib64/python2.7/site-packages/gi/**init**.py", line 100, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Vte not available

---

I still hope my changes help - and i would need a hint on how to get the development branch running on my PCs.

Gruss

### CODE REVIEW

**Comment by MeanEYE** [comment]
Thanks. I'll take a look and merge.h

**Comment by MeanEYE** [comment]
Okay, so I took a look at your changes. OpenSUSE complains because git1.2-vte is missing (most likely). Ubuntu is simply too old and doesn't have newer introspection files. At this point Ubuntu packages are almost 5 years old.

Opening files on FTP is fixed by another pull request I think, that's why GitHub is reporting conflict right now. Item sorting I'd like some clarification on your thought process.

**Comment by beschrade** [comment]
Please wait before trying to merge. I can run the development branch on OpenSUSE with Vte commented out, so i would like to test my changes to the development branch first.

Item sorting: Given a directory with lots of .c, .h, .png files. When sorting by extension the user expects the sorting to continue: within the same extension items should be sorted by name. The same is true for sorting by time: when i check out a git repo all files will have the same time displayed (!). Sorting by time should take intor account only the displayed part of the time (seconds dont count if only ours and minutes are displayed) within that order we need to sort by name, the order will otherwise appear to be random.

**Comment by beschrade** [comment]
Ubuntu 12.04: I will have a look at running on this release. It is a LTS release and will be around for at least another year.

**Comment by MeanEYE** [comment]
@beschrade what's the status of this. Should it be merged?

**Comment by cmallwitz** [comment]
Hi Bruno, 

I realized my PR #260 "Fix for issues #253 - Problems opening URL based filenames" addresses the same issue as your commit to application/associations.py 

My commit just checks if a file name starts with '/' rather than not starting with (reg ex) 'protocol://'. Can you think of any issue with either approach? I can't but I thought I might pop the question just in case...

Gruß
Christian

**Pull request closed without merging**
