### PR TITLE
show/hide titlebar option

### PR DESCRIPTION
**Pull request by multiSnow**
This PR add an option in 'Display -> Main Window' to control visibility of titlebar.

### CODE REVIEW

**Comment by MeanEYE** [comment]
What is the benefit of hiding title bar? Also, how would some of the controls be accessed?

**Comment by multiSnow** [comment]
The standard titlebar, which should provided by windows manager, could be hidden in some window manager, e.g. awesomeWM.
But since the titlebar of sunflower is not such a 'standard titlebar', it could not be hidden, and take a height of about two or three lines in item list.
This PR give a choice for users who are using sunflower in such a window manager to see more line in item list.
The controls, including main menu button, is not directly accessble, so titlebar is visible as default, and the preference dialog could be access by keybinding.

**Comment by MeanEYE** [comment]
Ah, okay, that makes sense. Could you provide me with a screen shot if it's not too much of a trouble. I'd like to make sure am not accidentally making a new problem. This option does sound useful and I will merge it.

**Comment by multiSnow** [comment]
In a 1366x768 screen, using awesome 4.3.

without titlebar:
hide_titlebar

with titlebar:
show_titlebar

**Comment by MeanEYE** [comment]
Are you using the latest version? Since I don't see any of the header bar controls for main menu, new tab, commands, etc.

This is how mine looks like:
image

**Comment by MeanEYE** [comment]
That said, we can add shortcuts to show those popups even with header bar hidden.

**Pull request merged**
