### PR TITLE
fake clipboard for item copy/cut/paste

### PR DESCRIPTION
**Pull request by multiSnow**
It is ***NOT*** a perfect solution.
Since https://gitlab.gnome.org/GNOME/gtk/issues/364 had been closed without any fix in gtk-3-24, it is the time to do something wiith the clipboard.

This PR provides a 'internal clipboard' to store the list of item(s), and return if required.
Following is the behavior definition:
1. Text copy/paste is not changed.
2. Any clipboard changing (including text copy by sunflower itself or text/data copy by other application) will reset the 'internal clipboard'.
3. Item copied by other application is not available to sunflower, and item copied by sunflower is not available to other application.
4. Item copy/cut/paste by sunflower only change the 'internal clipboard', and the 'real' clipboard is not touched (which may also contain text copied by sunflower).

This PR try to workaround #357.

### CODE REVIEW

**Comment by MeanEYE** [comment]
Thank you for your work. Before merging this solution I'd like to attempt in solving this problem in more compatible manner. Should I fail in doing so, I will merge this.

**Comment by multiSnow** [comment]
It is possible to get item copied by external application, since `wait_for_contents` is defined in gir-gtk.
But since `set_with_data` is not provided, copy item into clipboard seems not possible, means sunflower could never copy item to external application.

It may be better to let the fake `set_with_data` set a `Gtk.SelectionData`, and using the `wait_for_contents` from gir-gtk, so sunflower could get copied item from both external application and sunflower itself.
But since sunflower has some more powerful operation, such as filter and queue, copy/cut from external application would be complicate and risky.

**Comment by MeanEYE** [comment]
I wasn't planning on using `wait_for_contents`. My thinking was to either make our own library written in C and then import it directly into Python, thus going around GObject Introspection entirely.

Currently I am investigating which approaches other Gnome applications are using, since no GI based applications have access to `set_with_data`, including every Gnome extension and Gnome's own Polari client. Ideally I'd like to avoid writing a C library, but what must be done will be done.

Your solution would only partially fix the problem and bug reports will not stop coming in even if I merge this. So I have to try to find a more complete solution and save us from additional work in the future. If there's no other way, we'll implement this.

**Comment by MeanEYE** [comment]
[This](https://gist.github.com/MeanEYE/b6feea1e88abe95d06b876274a8a37cc) is my current progress. I continued testing from where @jaap-karssenberg stopped. For some odd reason `set_with_data` even though it sets data, no other application is able to see it and as a result `get_func` is never called.

This code directly calls `libgtk` and its `gtk_clipboard_set_with_data`. If you run it, you can see that regular `set_text` works, but `set_with_data` doesn't. Perhaps am missing something obvious.

**Comment by MeanEYE** [comment]
Sorry it took so long to address this. Basically I have created a framework which consists of multiple clipboard providers in order to allow functionality to exist on platforms where it's supported. Your fake clipboard is a great idea but it requires adapting for this new framework.

I will do this adaptation and commit the change under your name as you are the creator of it and credits need to be given where credits are due. Thank you once again for your work.

**Pull request closed without merging**
