### PR TITLE
use "monospace 10" in non-gnome environment

### PR DESCRIPTION
**Pull request by multiSnow**
In [Gio.Settings.new](https://lazka.github.io/pgi-docs/Gio-2.0/classes/Settings.html#Gio.Settings.new):

```
It is an error for the schema to not exist: schemas are an essential part of a program, as they provide type information. If schemas need to be dynamically loaded (for example, from an optional runtime dependency), Gio.SettingsSchemaSource.lookup() can be used to test for their existence before loading them.
```

This PR lookup 'org.gnome.desktop.interface' before load it, or use 'monospace 10' as system monospace font if 'org.gnome.desktop.interface' is not found (not in Gnome Desktop Environment).

### CODE REVIEW

**Comment by MeanEYE** [comment]
Thanks for submitting this. I'll take a look at it tomorrow as there are some things I'd like to be changed in this PR and am exhausted from today's work. 13h shifts are not making me eager to look at more code :).

**Comment by MeanEYE** [comment]
Sorry for the delay. Before I merge I'd like to ask few things in regard to this.

1. Why create a separate file only for this use;
2. Why use global variable/constant?

**Comment by multiSnow** [comment]
Using global variable so that the 'lookup' operation would done only once and the result, the name string of monospace font, could be used in VTE, file list, source viewer, and maybe other widget in the future.

I could not decide which file is better to place such a function. 'common.py' does not contain pygi module, and modules under 'tools' already as their own usage and has not relation with 'font'.

**Comment by MeanEYE** [comment]
I think I'd prefer this be under `common.py` if you don't mind moving it. Missing import is easily added.

**Comment by MeanEYE** [comment]
Thank you!

**Pull request merged**
