### PR TITLE
Terminal: fix argument passed to feed_child function

### LINKED ISSUE #234: GTK3 - Feeding directory name into terminal doesn't work
Pressing CTRL-LEFT/RIGHT in a file tab, with the other side having a terminal tab open, spits out:

```
Traceback (most recent call last):
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/accelerator_group.py", line 93, in _handle_activate
    result = callback_method(widget, label)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugin_base/item_list.py", line 1476, in _inherit_left_path
    opposite_object.feed_terminal(self.path)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugin_base/terminal.py", line 377, in feed_terminal
    self._terminal.feed_child(text)
TypeError: feed_child() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugin_base/item_list.py", line 632, in _handle_key_press
    result = PluginBase._handle_key_press(self, widget, event)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugin_base/plugin.py", line 288, in _handle_key_press
    result = group.trigger_accelerator(keyval, state)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/accelerator_group.py", line 215, in trigger_accelerator
    result = self._handle_activate(self._accel_group, self._window, keyval, modifier)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/accelerator_group.py", line 93, in _handle_activate
    result = callback_method(widget, label)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugin_base/item_list.py", line 1476, in _inherit_left_path
    opposite_object.feed_terminal(self.path)
  File "/home/christian/tech/IdeaProjects/Sunflower_develop/application/plugin_base/terminal.py", line 377, in feed_terminal
    self._terminal.feed_child(text)
TypeError: feed_child() takes exactly 3 arguments (2 given)

```

### PR DESCRIPTION
**Pull request by joshas**
While triaging issue #234 found a bit different issue and fixed it. This probably closes #234 too, as functionality mentioned in issue is working correctly.

### CODE REVIEW

**Comment by MeanEYE** [comment]
Hm, am not sure it fixes that issue as the complaint is about number of parameters. Did you test?

**Comment by joshas** [comment]
Maybe something changed in terminal package over the years, but I couldn't reproduce issue with number of parameters error.

**Comment by MeanEYE** [comment]
Hm, okay. Perhaps the issue is upstream and we only ran into it when we provided wrong data type.

**Comment by joshas** [comment]
Found a related bug, but with exactly opposite issue from 2018: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914720 .
And Vte docs also lists feed_child() function as accepting single argument: https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html#Vte.Terminal.feed_child

**Comment by MeanEYE** [comment]
Yes, I think I've ran into this already. Forgot how I solved it in a different place, but this does seem to be fixing linked issue.

**Pull request merged**
